/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import modelo.bean.Paciente;
import modelo.bean.Medico;
import modelo.dao.PacienteDAO;
import modelo.dao.MedicoDAO;

/**
 *
 * @author ASUSX451
 */
public class TelaExcluirMedico extends javax.swing.JInternfw,ê‚ïdtIU2)publico extroupa = newlico ex();)publico ex;

troupa;

t= newlico ex;

();))publ
 *
     * Cres
 ******formlaExcluirMedClteDAO
     */
    lic claaExcluirMedico ex()IU2        initCort neDAs();)publ}))publ
 *
     * T temmer Ad temcalled frsGo Cres
 ******formlaExcluirMedClteDAO
     */
    lic claaExcluirMedico ex()IU2        initCort neEmport modelo.construcderSo e
ƒ³;cmnC open th zu(ort modellaaExcluirMedico ex()IU2        initCort neEmport modelo.construcderSo e
ƒ³;cmnC open th zu(ort modellaaExcluirMedico ex()IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  IU2  Jdform omOT  * ifynternfc* T. IUU2  IExct ofnternfIU2  IU2  alwaysIU2  IU2prhVŠ6?Äésbrrt d byIU2  Ft moEx;

();)
ƒ³;cmnC o@SuppressWarn   s("unchecked")U2  IU/T}ex;

(-fold defaultstrt ="collapsed" desc="Gésbrrt d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="Gés d Cnsc="GéJr5!@EGIN:  Ft moEx;

()U2  alrivdCltvoid2  Ft moEx;

();)  IU2  IIIIIjScrd CqrEg L2  al CqrEg L2v(1ceIIjScrd CqrEg das="Gés d Cnsc="\ˆrQÐŒ§xEù,Çéx:ctabel4rEg das="Gés d Cnsc=tabelÐŒ§xEù,Çéx:cbPesquisarrEg das="Gés d Cnsc=ButtonÐŒ§xEù,Çéx:ctfés igoPesquisarEg das="Gés d Cnsc=TExcFieldg L2v(1ceIIjScrd C2rEg das="Gés d Cnsc="\ˆrQÐŒ§xEù,Çéx:ctabel2rEg das="Gés d Cnsc=tabelÐŒ§xEù,Çéx:ctfés igorEg das="Gés d Cnsc=TExcFieldg L2v(1ceIIjStabel3rEg das="Gés d Cnsc=tabelÐŒ§xEù,Çéx:ctf\ rU§xEù,Çéx:ctf\ rU§xEù,Çéx:ctf\ rU§xEùdfooEx;

();)
ƒ³;cmnC o@SuppressWarn   s("uncheckñ&–=ãn   s("uncheckñtDoe¬—!¦(’axe~ìz!Àüë!wÛÜñ»;µú²ˆ0MC ope d Cnsc=ButtonÐŒ§xEù,Çéx:ctfés igoPesquisarEg das="Gés d Cnsc=TExcFieldg L2v(1ceIIjScbApag das="Gés d Cnsc=tabelÐŒ§xEù,Çéx:cbPesqubCancOT das="Gés d Cnsc=tabelÐŒ§xEù,ÇéCtsetClosable()
eÐŒ§xEù,ÇéCt);)  IU.setBtemg2  nd(OT das=".awt.Color(123, 10, 10)Ft moEx;

();)  IU.setBor***(as="Gés d Cn.setBoico ex()IU2        initCort neEmport modelo.construcderSo ely.cdformTit"uneEmportnull, "uisarrEg dU2  I",Eù,ÇéCt);)  IbEmpor.Tit"uneEmpor.DEFAULT_JUSTIFICATION,Eù,ÇéCt);)  IbEmpor.Tit"uneEmpor.DEFAULT_POSITION,Eor***(as="GésF="G("Dtstog",Eco e1),**(as="Gés d Cn.white()Insc=NOI19OT das="Gés d Cnsc=tabelÐŒ§xEù,ÇéCtsetClosable()
eÐŒ§xEù,ÇéCt);)  IU.setBtemg2  nd(OT das=".awt.Color(123,ÇéCaxEù,Çiöð®‘wneCttemg2  nd(OT das=".awt.Color(123,ÇéCaxEù,Çi.cdformTit"uneEmportnull, "uisarrE255, 255, 255)ctfés igoPesquisarÇiöð®‘wneCttemg2  nd(OT das=".awt.Coloés igoPesquisarÇiöðù,Çé("In="Gée   *Ã³:ctf\aULT_PO:"olor(123,ÇéCaIjScrd C2rÇiöðù,Çé("jScrd C2r"ldg L2v(1ceIIjScrd C2r.addAc)IU2Lis<E C2r"ldglL2vsE L2v..addAc)IU2Lis<E(-fold defauuuuuuncheck"Gés aaddAc>aeXÔåÏB«¹Q ÍÑW°ûm½ƒþÀh?“?#ñgö§?ùé§ C2rÇiöðù,Çé("jScrd C2r"ldg L2v(rdg L2v(rdg L"jScrd C2r"ldg L2v(rdg L2FsoreAi C2rÇiöðù,Çé("jg L";crd C2r"ldg L}crd C2r"l}2r"ldg L2v(1clÐŒ§xEù,ÇéGjScrLayoutt.Color(LayouttneEmport modelo.coUU2  IExct ofnternfIU2  IU r"DU2  IExct ofnternfIU2  IU r"DU2  IExct ofntet.Color(ofnternfIU2  IU r"Color(DU2 H123z3,Çal2  IU("l}2r"ldg L2v  IU r"Color(DsF="G(Parnsc=l2  IU(t ofnternfIU2  IU r"DU2.AlignmScrdLEADd C<U(t ofnternfIU2  IU r"DU2.AligarheL(DsF="G(Parnsc=l2  Sequ<U(i2r"ldg L)rÇiöðù,Çé("jg L";2.Aliap(109Empo9Empo9)rÇiöðù,Çé("jg L";2.AligarheL(DsF="G(Parnsc=l2  IU(t ofnternfIU2  IU r"DU2.AlignmScrdLEADd C<U(t ofnter, false)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZE,IU2  IU r"DU2  IExct ofn(OT das="SIZE,ISIU2t.MAX_VALUE)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,xcFieldg L2v(1ce,IU2  IU r"DU2  IExct ofn(PREFERRED"SIZE,I);)  U2  IU r"DU2  IExct ofn(PREFERRED"SIZE))rÇiöðù,Çé("jg L";2.Aliap(4rnf xlr))rÇi(4rnf dé("jg L"; L";2.AhVŠEeldg L2v(1ce,IU2  IU r"DU2  IExct ofn(PRE ofn(PREFERRED"SIZE))rÇfntiuunIU rEg das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZE ofn(PREFxct ofnternfIU2  IU r"DU2  IV/
  ctet.Color(ofnternfIU2  IU r"Color(DU2 H123z3,Çal2  IU("l}2r"ldg L2v  IU r"Color(DsF="G(Parnsc=l2  IU(t ofnternfIU2  IU r"}2r"ldg L2v  IU r"Color(DsF="G(PaTRAIL=l2  "DU2.AlignmScrdLEADd C<U(t ofnternfIU2  IU r"DU2.AligarheLrÇfntiuunIU rEg das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZ ofn(PREFERRED"SIZE))rÇiöðù,Çé(" C<U(tFERRED"SIZE,I);)  U2  IU r0etBte0  Sequ<U(i2r"ldg L)rÇiöðù,Çé("jg L";2.Aliap(109Empo9Empo9)rÇiöðù,Çé("jg L";2.AligarheL(DsF="G(PaziSEL=lIZE,IU2  IU r"DU2  IExct ofn(OT das="SIZE,ISIU2t.MAX_VALUE)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,xfnter, false)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I  IExct ofn(PRE ofn(PREFERRED"SInt"caû@2ŒÈk²,VEfÈÖ›6J	`NC€b aeRE ofn(PREFERRED"SInt."SInt"h3Ms="Gés d Cnsc="\**(as="Gés d Cn.setBoico ex()IU2        initCort neEmport model2.construcderSo ely.cdformTit"uneEmportnull, "uisarrEg dU2  I",EDados da  IbEmpor.Tit"uneEmpor.DEFAULT_JUSTIFICATION,Eù,ÇéCt);)  IbEmpor.Tit"uneEmpor.DEFAULT_POSITION,Eor***(as="GésF="G("Dtstog",Eco e1),**(as="Gés d Cn.white()Insc=NOI19OT das="Gés d Cnsc=ts="Gés d Cnsc=tadas=".awt.Color(123,ÇéCaxEù,Çiöð®‘wneCttemg2  nd(OT das=".awt.Col2r(123,ÇéCaxEù,Çi.cdformTit"uneEmportnull, "uisarrE252wt.Coloés ¬—!¦(’axwneCttemg2  nd(nsc=tadas=".awt.Color(123,ÇéCaxEù,Çiöð®‘wneCttemg2  nd(OT das=".awt.Col3r(123,ÇéCaxEù,Çi.cdformTit"uneEmportnull, "uisarrE253wt.Coloés ireÃ§owneCttemg2  nd(nsc=t***(as="Gés d Cn.setBoico ex()IU2  DEFAULT_POSITION,Eor***(as="GésF="G("Dtstog",Eco e1),**(asemn"GésF="G("Dtstog"arrE252wt.Coloés ¬—!¦(’axwneð®‘wnentiMD"SIZE))rÇfntiuunIU rEg das="G(semn"GésF= igoPetog"arrE252wt.CþÀh?“?#ñgö§?ùé§ C2rÇiöðù,Çé(2jScrd C2r"ldg L2v(rdg L2v(rdg L"jScrd C2r"l2tBoico ex()IU2        L"jScrd C2r"l2L";crd C2r"ldg L}crd C22"l}2r"ldg L2v(1clÐŒ§xEù,ÇéGjScrLayoutt.Color2g das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZE ofn(PREFxct ofnternfIU2  IU r"DU2  IV/
  ctet.Color(ofnternfIU2  IU r"Color(DU2 H123z3,2al2  IU("l}2r"ldg L2v  IU r"Color(DsF="G(Parnsc=l2  IU(t ofnternfIU2  IU r"}2r"ldg L2v  IU r"Color(DsF="G(PaTRAIL=l2  "DU2.AlignmScrdLEADd  IU r"DU2  I2g das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZE ofn(PREFxct ofnternfIU2  IUG(Parnsc=l2  IU(t ofnternfIU5fnternfIU2  IUG(Parnsc=l2  IU r"DU2  I2g das="G(,Çé("ldg L2v  IU r"Color(DsF="G(ParnscnmScrdLEADd  IU r"DU2  I2g das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZE ofn(PREFxct ofnternfIU2  IUG(ParnscG(Parnsc=l2  IU(t ofnternfIU2fnternfIU2  IUG(ParnscG(Parnsc=l2  IU(t ofnternfIU3fnternfIU2  IUG(ParnscG(Parnsc=l2  IU(t ofnternfIU1PREFERRED"SInt"caûnmScrdLEADd  "l}28Dts8Dts8olor(DsF="G(ParnscnmScrdLEADd  IU r"DU2  I2g das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZE ofn(PREFxct ofnternfIU2  IUG(ParnscG(Parnsc=l2  IU r"DU2  I2g das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZE ofn(PRolor(DU2fnternfIU2  IUG(ParnscG(Parnscrnsc=l2  IU(t ofnte,Çéx:ct,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  IUdas="G(,Çé("jS,IU2  I  IExct ofn(PRE ofn(PnternfIU2  IUG(ParnscG(Parnscrnsc=l2  IU(t ofnte,Ç igoPe,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  IU r"DU2  IExct ofn(OT das="SIZE,IU2  IU r"DU2  IExct ofn(OT dG(Parnscrnsc=l2  IU(t ofnte,Çtnull, "u,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I46jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I46jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I46jg L"; L";2.AlEg das="G(,Çé("jS,IUbCrnfIU1PREFERRED"SInt"caûnmScAlEg e"jS,IU2  I46jg L"; L";2.AlEIZE))rÇiöðù,Çé("jg L";2.Aliap(4rnf xlr))rÇi(4rnf de.csS,IU2  I46jg L"; L";2.AlEg das="G(,Çé("jS,IUbCrnfIU1PREFERRED"SInt"caûnmScAlEg e"jS,IU2  I46jg N If 
Dn(OT das="SE ofn(PREFxct ofnternfIU2  IU r"DU2  IV/
  ctet.Color(ofnternfIU2  IU r"Color(DU2 H123z3,2al2  IU("l}2r"ldg L2v  IU r"Color(DsFg L2v  IU r"Color(DsF="G(PaTRAIL=l2  "DU2.AlignmScrdLEADdRED"3,Çt3,Çt3,ZE ofn(PREFxct ofnternfIU2  IUG(Parnsc=l2  IU(t ofnternfIU5fnternfIU2  IUG(Parnsc=l2  IU r"DU2  rÇiöðù,Çé("jg L";2.AligarheL(DsF="G(PaziSEL=lIZE,IU2 2  IExct ofn(OT das="SIZE,ISIU2t.MAX_VALUE)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,xfnter, false)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I  IExct ofn(PDU2  I2g das="G(,Çé("jS,IEADdRED"3,Çt3,Çt3,ZE ofn(PREFxct ofnternfIU2  IUG(Parnsc=l2  IU(t ofnternfIU5fnternfIU2  IUG(Parnsc=l2  IU r"DU2  rÇiöðù,Çé("jg L";2.AligarheL(DsF="G(PaziSEL=lIZE2  I46jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I46jg L)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,xfnter, false)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I  IExct ofn(PDU2  22g das="G(,Çé("jS,IEADdRED"3,Çt3,Çt3,ZE ofn(PREFxct ofnternfIU2  IUG(Parnsc=l2  IU(t ofnternfIU5fnternfIU2  IUG(Parnsc=l2  IU r"DU2  rÇiöðù,Çé("jg L";2.AligarheL(DsF="G(PaziSEL=lIZU r"DU2  IExct ofn(OT dG(Parnscrnsc=l2  IU(t ofn)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,xfnter, false)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I  IExct ofn(PDU2  52g das="G(,Çé("jS,IEADdRED"3,Çt3,Çt3,ZE ofn(PREFxct ofnternfIU2  IUG(Parnsc=l2  IU(t ofnternfIU5fnternfIU2  IUG(Parnsc=l2  IU r"DU2  rÇiöðù,Çé("jg L";2.AligarheL(DsF="G(PaziSEL=lIZfn(PnternfIU2  IUG(ParnscG(Parnscrnsc=l2  IU(t )rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,xfnter, false)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I  IExct ofn(PDU2  32g das="G(,Çé("jS,IEADd  IU r"DU2  I29 rEg das="G(,Çé("jS,IU2  IU r"DtabelÐŒ§xEù,ÇéCodel2.construcderSo ely.cdformTit"uneEmportnull, "uisarrEg dU2 3I",EDados da  IbEmpor.Tit"uneEmpor.DEFAULT_EtchIFICATION)Gée   *Ã³:ctf\tBtemgI",EIcon(}crd C22"l}2r"ldImageIcon(gex()ass().gexResource("/imagens/r"Dete_ter.png");)  IU.setBtemg2  nd(OT\tBtemgI",EL"jScrtBtemg C2rÇiöðù,Çé("tBtemgIldg L2v(1ceIIjScrd C2r.addAc)IU2Lis<E C2r"ldglL2vsE L2v..addAc)IU2Lis<E(-fold defauuuuuuncheck"Gés aaddAc>aeXÔåÏB«¹Q ÍÑW°ûm½ƒþÀh?“?#ñgö§?ùé§ C2rtBtemg"jScrd C2r"ldg L2v(rdg L2v(rdg L"jScrd C2r"ldg L2v(rdg L2FFFFFFFFFFo/oaadcmg"jS2"l}2r"ldImageIcon(gex()ass().emg"jScrd C2n(OT das w(PDU2;aD@E< ofnter"SInt."SInt"h3rd C2r"ldg L2v(rdg L2FFFFFFFFSFICATION,Eù,ÇéCt);)  IbEmpor.Tit"uneEmpor.DEFAULT_POSITIOados da  IbEmpor.TicIsc=l2  IiBc";2.AlEg das="G(,Çé("jS,IU2  I46jg L"; L";2.AlEg das="G(,Çé("jS,IUbCrnfIU1PREFERRED"SInt"caûI",EDados da  IbEmpor.Tit"uneEmpor.DEFAULT_JUSTIFr- (I",EDados da reemgI",EL"jScrtBtemg C2rÇiöðù,Çé("txnt(eoPuWiD0gI",EL"jScrtBtemg C2rÇiöðù,Çé("txnt(eoPuWiD0gI",Eos da reemgI",EL"jScrtmuWiD0gI",EL"jScrtBtemg C2rÇiöðù,Çé("txnt(eoPuWiodos dc=l2  IiBc";2.AlEg das="G(,Çé("jS,IU2  I46jnfIg das="G(
das="G(
das="G(
das="G(
das="RED"3,Çt3,Çt3,ZE ofn(PREFxct ofnternfIU2  IUG(Parnsc}vadoofn(PREFxct ofnternfIUlEg dados da  IbEmp6jg L"; L";2.AlEg das="G(,ÇlEg dados da  IbEmp6AULT_POc=l2  IU(t ofnternfIU2  IU IU5 IU5 I(Parnsc=l2  IU r"DU2  rÇnd(OT\tBtemgI",EL"jScrtlrÇiöðù,Çé("tBtemgIldg L2v(1ceIIjScrd2  3      
das(2  IExct ofn2  3      
das(2dglL2vsE L2l)IU2Lis<E(-fold luuncheck"Gés aaddAc>aeXÔåÏB«¹Q ÍÑW°lEDados da reemgI",EL"jScrtBtemg C2rÇiöðù,Çé("txnt(eoPuWiD0gI",EL"jScrtBtemg C2rÇiöðù,s da  IbEmpE,I);)defauuuuuuncheck"Gés aaddAc>aeXÔåÏB«¹Q ÍÑW°ûm½ƒþÀh?“?#ñgö§?ùé§ C2rÇiöðù,Çé("jScrd C2r"ldg L2v(rdg L2v(röðù,s da  IbEmpE,I);"Color(DU2 H123z3,Çal2  IU(c>aeXÔåÏB«¹Q ÍÑW°ûm½ƒþÀh?“?#ñgö§?ùé§ C2rÇiöðù,Çé("jScrd C2r"ldg L2v(rdg L2v(röðù,s da  IbEmpE,I);dg L2v  IU r"Color(DsF="G(PdoPuWiodos dc=liodos dc=liodos dc=liodos dc=liodos dc=liodos dc=liodos dc=liodos dc=liodos dc=liodos dc=liodos dEFAÏB«¹Q ÍÑW°lEDados da reemgI",EL"jScrtBtemg C2rÇiöðù,Çé("txnt(eoPuWiD0gI",EL"jScrtBtemgreemgIlD0gI",EL"jScrtBtemg C2rÇiöðù,Çé("txnt(eoPuWiodos dc=2rÇiöðù,s da  IbEmpE,I);)defauuuuuuncheck"jS,IU2  IU r"DU20nfIU2  IUG(ParnscG(Parnsc=l2  IU(t ofnternÇé("txnt(eoPuWiodos dL)rferredFAULT_POSITION,Earnsc=Style.c=2rÇiöðùPlacetxnt(RELATED,Çé("txnt(eoPuWiodos dc=2rÇiöðù,s da  fIU2  IU r"Color(DU2 H123z3,Çal2  IU("l}2 false)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I  IExct ofn(PDU2  22g das="G(,Çé("jS,IEAos dL)rferredFAULT_POSITION,Earnsc=Style.c=2rÇiöðùPlacetxnt(RELATED,Çé("txnt(eoPuWiodos dc=2rÇiöðù,s da  nfIU2  IUG(ParnscG(Parnsc=l2  IU(t ofnter false)rÇiöðù,Çé("jg L"; L";2.AlEg das="G(,Çé("jS,IU2  I  IExct ofn(PDU2  22g das="G(,Çé("jS,IEAos dc=l2  IiBc";25AlEg das="G(,Çé("jSIU5 IU5 I(Parnsc=l2  Ifn(OT("js2.A0(PaziS5123z57mg2  nd(} ini/tCort neEmport modcr.DEFAULT_JUSTIFr- (I",EDados da reemgI",EL"jScrtBtemg C2rÇiöðù,Çé("txnt(eoPuWiD0gI",EL"jScrtBtemg C2rÇiöðù,Çé(osrrrrrrrrrrrr"mgI",EL"j(as="Gés d Cn.white()Insc=N_ter.png");)  IU.setBtemg2  nd(OTtBtemgFIRST:);)  _(as="Gés d Cn.white()Insc=a reemgI"tryfynternfc* TTTTTù,Çé(    */
    lic claaExclernfc* TTTTTù,Çé( */ù,Çé(   .buscarUmaR,Çé((ewliger.parseIer.parseIer.parseIerIRST:);)  _(as="Gés d Cn.white()Insûm½ƒþÀh?“?#ñgö§?ùé§ C2rtBtemg"jScrd C2r"ldg L2v(rdScrd C2r"aö§?ùé§ C2rtBtemg"jScrd C2r"ldg L2v(rdScrd C2r"aö§?ùé§ C2rtBtemg"jScrd C2r"ldg L2v(rdScrd C2r"aöGAerd C2r"ltoStr",E(2r"aö.“?#ñgcrd _2r"aög"jScrd C2r"ldg L2v(rd  rÇiöðùC2r"aöGAe2r"aö.“?#ñ  rÇiöðù(jScrd C2r"ldg L2v(rrÇiöðùC2r"aöGAe2r"aö.“?#rÇiöðùö.“?#ñ  rÇiöðù(jScrdG;lace2r"aö§?ùé§ C2rtBtemg"jniöðùö.“?#ñ  rÇiSdos rd C2rr"ldg L2v(rdScrd C2r"aé§ C2rtBttBtemg2  T das=".awt.C} caL"; (Excelico  eXÔåÏB«¹Q ÍÑW°ublico extr.showMesss()EfÈÖ›(i\nB«¹Q ÍÑW°ublico extr.s IU r"Color(DsF="G(P W°ublico(Parnsc=l2  IU(t ofnternÇé("gce2r" fIU2  IU r"Color(DU2 H123z3,Çal2  IU("l}2 false)rÇiöðù,Çé("jg L"; L";2.AlEg das=" + **(as="Gés d}

arseIerIr"ldLA2v(rdScrd C2r"aö§?ùé§ C2rtBtemg"jScrh?“?#ñgö§?ùé§ C2rtBResource("/imagens/r"DScrd C2r"aö§?ùé§ C2rtBtemg"jScrd C2r"ldg L2v(rdScrd CResource("/imagens/r"
rd C2r"ldg L2v(#ñgcrd _2r"aög"jScrdt modellaaExcluirMrd _2r"aög"jSco(P"aö§?ùé§ C2rt2r"aöGAe2r"aö.“?#ñ  rÇiöðù2r"ldg L2v(rrÇrdScrd C2r"aöGAerd C2r"ltoStr",E(2r"aö.“?#ñgcrd _2r"aög"jSldg e2  IU2nB«¹QrrÇrdScrd C2r"aö123z3,Çal2  IU("l}2 false)rÇiöðù,Çé("Çiöðù e2  IUda com suc}2 o!"rrÇiöðùC2r"aöGAe2r"aö.“?#rÇiöðùö.""rrÇiöðùC2r"aöGAe2r"ÇiSdos rd C2rr"ld""rrÇiöðùC2r"aöGAe2rdas=".awt.C} ca""rrÇiöðùC2r"aöGAe2rico extr.showM=l2  IU(t ofnternÇé("gce2r" fIU2  IU r"Color(DU2 H123z3,Çal2  IU("l}2 false)rÇiöðù,Çé("jg L"; Le2  IU2 crt moddas=" + **(as="Gés d}

arseIerIr"ldLA2v(rdScrd CResource("/imagens/r"
rd C2ñgö§?ùé§ C2rtB C2n(OT das w(PDU2;aD@E<Scrd C2r"aö§?ùé§ C2rtBtemg"jScrd C2r"ldg L2v(rdScrd C C2n(OT das w(PDU2;aD@E IU(t ofntdisposesarEg daserIr"ldLA2v(rdScrd C C2n(OT das w(PDU2;aD@E Ig dasrIRVas rs()s decOT afIU2 - do notnfIU2  tnfIU2  tnfIfntco e afIU2"decOT afIU2 - do notnfIU2  tnfIU2  tnfIfntco e afIU2"decOT afIU2 - do notnfIU2  tnfIU2  tnfIfntco e afIU2"decOT afIU2 - do o4UdisfIU(Parns3 afIU2"decOT afIU2 - do o4UdisfIU(Parns4 afIU2"decOT afIU2 - do o4UdisfIU(Parns5 afIU2"decOT afIU2 - do o4UN_ter rEg das afIU2"decOT afIU2 - do o4UN_ter rEg dae afIU2"decOT afIU2 - do o4UN_ter rEg da3 afIU2"decOT afIU2 - do o4Us d Cnsc=Cnsc="Gés d  afIU2"decOT afIU2 - do o4Usc=TExScrd C2r" afIU2"decOT afIU2 - do o4Usc=TExScrg dasrIR afIU2"decOT afIU2 - do o4Usc=TExScrh?“?#ñgö afIU2"decOT afIU2 - do o4UsWarn   srÇiöðùC2r"aöG afIU2"decOT afIU2 - do o4UsWarn   srÇiöðr"aöG afIU2"decOT afIU2 - do o4UsWarn   srÇiöðr"aöGh?“?#ñg afIU2"decOT afIU2 - do o4UsWarn   srÇiö2r"aöG afIU2"decOT afIU2 - do o4UsWarn   srÇiöfnter;fIU2 - dEes
 f v notnfIU2  tnfIU2  th?“?#ñgö§ - do notn}
